language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t xiarnousx/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true xiarnousx/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-124608211804"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRETE_KEY"
