sudo: required
services:
  - docker


  before_install:
    - docker build -t xiarnousx/docker-react -f Dockerfile.dev . 
  
  script:
    - docker run xiarnousx/docker-react npm run test -- --coverage
  
  